### ISSUE TITLE
User / Profile Bootstrap Gulp Task

### ISSUE THREAD

**Issue by ne0fite** [ne0fite/GigKeeper#19]
Create a gulp task that will create a profile and account. It only requires an email address and password for input and generates a new profile and user record.

**Comment by zero-degrees** [comment]
I'm not sure Gulp [is a good fit for this](https://www.npmjs.com/package/gulp).  It sounds like it the kind of thing that would normally be handled with a web interface or shell script.

**Comment by ne0fite** [comment]
It's a system setup task, really. So instead of executing SQL to create an initial account.
