### ISSUE TITLE
Specify starting location

### ISSUE THREAD

**Issue by zero-degrees** [ne0fite/GigKeeper#45]
Estimates are currently calculated with the user's home location as the starting point for every trip.  If a musician is on tour, they will need a way to easily change it.

**Comment by ne0fite** [comment]
Might be useful to have a choice of home base, select another gig, or enter another location. But most likely, you're coming from home or another gig.

**Comment by ne0fite** [comment]
With the new route selector UI, perhaps a radio option at the top of the page to select home base or another gig's location from a drop-down.

**Comment by zero-degrees** [comment]
This feels like it belongs on gigEdit, since that's where the destination is specified.

**Comment by ne0fite** [comment]
Good point. Agreed.

**Comment by ne0fite** [comment]
Updated the UX a bit. Provided the ability for the user to specify whether they are coming from home, another gig, or from someplace else.

Selecting home resets the origin place to the user's profile home base place.

Selecting another gig reveals a drop down to select another gig. Selecting the gig updates the origin place with that gigs location place.

Select someplace else reveals the google place selector to find another location.

The origin type and gig are stored with the gig.

**Comment by ne0fite** [comment]
May need to revisit the gig drop down UX to make it easier to find a gig, but the issue has been addressed.
