### ISSUE TITLE
Emails are case-sensitive

### ISSUE THREAD

**Issue by zero-degrees** [ne0fite/GigKeeper#75]

**Comment by ne0fite** [comment]
Do you mean as usernames for logging in?

**Comment by zero-degrees** [comment]
Everywhere we currently use them.

**Comment by ne0fite** [comment]
These are the use cases I found where we compare email:

- Login
- Forgot Password
- Invite: pre-existing account check
- Invite: pre-existing invite check
- Registration: pre-existing account check
