### ISSUE TITLE
Improve Frontend Session Management

### ISSUE THREAD

**Issue by ne0fite** [ne0fite/GigKeeper#8]
Need better session management in the frontend. If the page navigates before the profile is loaded, the navigation bar does not show certain menu items requiring a logged-in session. There needs to be a better way.

**Comment by zero-degrees** [comment]
I suggest [angular-local-storage](https://github.com/grevory/angular-local-storage).  It allows us to bind scope variables to localStorage, so the code changes will be minimal.  I have used this lib before, and it worked well.
